default:
  http_metas:
    content-type: text/html

  metas:
    title:        symfony project
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [main]

  javascripts:    [jquery-2.1.3.min.js, /FormBuilderGui/FormBuilder.js, /FormBuilderGui/Form.js, /FormBuilderGui/FormTypes.js, /FormBuilderGui/FormFields.js]

  has_layout:     on
  layout:         layout
